version: '3.9'
services:
  gitea:
    image: gitea/gitea:1.20
    restart: always
    environment:
      USER_UID: 1000
      USER_GID: 1000
      GITEA__database__DB_TYPE: postgres
      GITEA__database__HOST: postgres:5432
      GITEA__database__NAME: gitea
      GITEA__database__USER: gitea
      GITEA__database__PASSWD: gitea
    volumes:
      - './volumes/gitea_data:/data'
    ports:
      - '127.0.0.1:8300:3000'
    depends_on:
      - postgres

  postgres:
    image: postgres:14
    restart: always
    environment:
      POSTGRES_USER: gitea
      POSTGRES_PASSWORD: gitea
      POSTGRES_DB: gitea
    volumes:
      - './volumes/postgres_data:/var/lib/postgresql/data'

  nginx:
    image: nginx:latest
    restart: always
    depends_on:
      - gitea
    volumes:
      - ./nginx_templates:/etc/nginx/templates
      - ${NGINX_LOG_DIR:-}:/logs
    environment:
      - NGINX_ENVSUBST_TEMPLATE_SUFFIX=.nginx

  cloudflared:
    image: cloudflare/cloudflared:latest
    command: tunnel run
    restart: always
    depends_on:
      - nginx
    environment:
      TUNNEL_TOKEN: ${CLOUDFLARED_TUNNEL_TOKEN:-}
