services:
  gitea:
    image: gitea/gitea:1.21.9
    restart: always
    deploy:
      resources:
        limits:
          cpus: '1.00'
          memory: '2G'
    environment:
      USER_UID: 1000
      USER_GID: 1000
      GITEA__database__DB_TYPE: postgres
      GITEA__database__HOST: postgres:5432
      GITEA__database__NAME: gitea
      GITEA__database__USER: gitea
      GITEA__database__PASSWD: gitea
    volumes:
      - './volumes/gitea_data:/data'
    depends_on:
      - postgres
    logging:
      driver: fluentd
      options:
        tag: docker.gitea_aoirint_com.gitea.{{.ID}}
        fluentd-async: "true"

  postgres:
    image: postgres:14
    restart: always
    environment:
      POSTGRES_USER: gitea
      POSTGRES_PASSWORD: gitea
      POSTGRES_DB: gitea
    volumes:
      - './volumes/postgres_data:/var/lib/postgresql/data'

  nginx:
    image: nginx:latest
    restart: always
    depends_on:
      - gitea
    ports:
      - '127.0.0.1:8300:80'
    volumes:
      - ./nginx_templates:/etc/nginx/templates
      - ${NGINX_LOG_DIR:-}:/logs
    environment:
      - NGINX_ENVSUBST_TEMPLATE_SUFFIX=.nginx
    logging:
      driver: fluentd
      options:
        tag: docker.gitea_aoirint_com.nginx.{{.ID}}
        fluentd-async: "true"

  cloudflared:
    image: cloudflare/cloudflared:latest
    command: tunnel run
    restart: always
    depends_on:
      - nginx
      - gitea
    environment:
      TUNNEL_TOKEN: ${CLOUDFLARED_TUNNEL_TOKEN:-}
